name: Testing
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: testing the steps
        run: echo " Hello Rushabh "
      - name: testing Ls
        run: ls
      - uses: actions/checkout@v4
      - name: Testing ls With action
        run: ls


